# Generated by Django 3.0 on 2021-12-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availbale',
            new_name='is_available',
        ),
    ]
